phone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from .views import UserListView, UserDetailView, UserCreateView, UserUpdateView, UserDeleteView, SearchResultsView

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('create', UserCreateView.as_view(), name='user_create'),
    path('<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete', UserDeleteView.as_view(), name='user_delete'),
    path('search/', SearchResultsView.as_view(), name='search_results'),

]

users/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Users(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    phone = models.TextField(max_length=20)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Users, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} {self.surname}"

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.id])

users/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from .models import Users


class UserListView(ListView):
    model = Users
    template_name = 'users/user/user_list.html'
    context_object_name = 'users'


class UserDetailView(DetailView):
    model = Users
    template_name = 'users/user/user_detail.html'


class UserCreateView(CreateView):
    model = Users
    fields = ['name', 'surname', 'phone']
    template_name = 'users/user/users_form.html'


class UserUpdateView(UpdateView):
    model = Users
    fields = ['name', 'surname', 'phone']
    template_name = 'users/user/users_update.html'


class UserDeleteView(DeleteView):
    model = Users
    success_url = '/'
    template_name = 'users/user/user_delete.html'


class SearchResultsView(ListView):
    model = Users
    template_name = 'users/user/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Users.objects.filter(
            Q(name__icontains=query) | Q(surname__icontains=query) | Q(phone__icontains=query)
        )
        return object_list

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div id="content">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

users/templates/users/user/search_results.html
{% extends "users/base.html" %}
{% block title %}Search results{% endblock %}

{% block content %}
    <h1>Search Results</h1>
    <ul>
        {% for user in object_list %}
            <li>
                {{ user.name }} {{ user.surname }}: {{ user.phone }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

users/templates/users/user/user_delete.html
{% extends "users/base.html" %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <a href="{% url 'users:user_list' %}">Home</a>

    <form method="POST">
        {% csrf_token %}
        <h2>Delete {{ object.name }}</h2>
        <button type="submit">Delete</button>
        <a href="{% url 'users:user_detail' object.id %}">Cancel</a>

    </form>
{% endblock %}

users/templates/users/user/user_detail.html
{% extends "users/base.html" %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <a href="{% url 'users:user_list' %}">Home</a>
    <h1>{{ object.name }} {{ object.surname }}</h1>
    <p>Phone number: {{ object.phone }}</p>
    <a href="{% url 'users:user_update' object.id %}">Update user</a>
    <a href="{% url 'users:user_delete' object.id %}">Delete user</a>

{% endblock %}

users/templates/users/user/user_list.html
{% extends "users/base.html" %}
{% block title %}Phone Data{% endblock %}
{% block content %}
    <a href="{% url 'users:user_create' %}">Create user</a>
    <form action="{% url 'users:search_results' %}" method="get">
        <input name="q" type="text" placeholder="Search...">
    </form>
    <h1>Phone Data</h1>

    {% for user in users %}
        <h2>
            <a href="{% url 'users:user_detail' user.id %}">{{ user.name }} {{ user.surname }}: {{ user.phone }}</a>
        </h2>
    {% endfor %}
{% endblock %}

users/templates/users/user/users_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <form method="POST">
    {% csrf_token %}
    <h2>Create user</h2>
    {{ form|crispy }}
    <button type="submit">Create</button>
    </form>
{% endblock %}

users/templates/users/user/users_update.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <form method="POST">
    {% csrf_token %}
    <h2>Update {{ object.name }}</h2>
    {{ form|crispy }}
    <button type="submit">Update</button>
    </form>
{% endblock %}